const MAP_CONST = {
  MIN_LOCATIONS: 25,
  MAX_LOCATIONS: 100000,
  MAX_NAME_LENGTH: 30,
  MIN_NAME_LENGTH: 3,
  MAX_SHORT_DESCRIPTION_LENGTH: 100,
  MIN_SHORT_DESCRIPTION_LENGTH: 20,
  MAX_LONG_DESCRIPTION_LENGTH: 1000,
  MIN_LONG_DESCRIPTION_LENGTH: 100,
  MIN_MAP_INTERVAL: 3600000 // 1 hour
};
export default MAP_CONST;