// GENERATED by scripts/writeCountryMapList.mjs from public/officialCountryMaps.json.
// Do not edit by hand; rerun the script when a country map is added.
export const COUNTRY_MAP_LIST = [
  {
    "name": "Albania",
    "slug": "albania",
    "countryCode": "AL"
  },
  {
    "name": "Andorra",
    "slug": "andorra",
    "countryCode": "AD"
  },
  {
    "name": "Argentina",
    "slug": "argentina",
    "countryCode": "AR"
  },
  {
    "name": "Australia",
    "slug": "australia",
    "countryCode": "AU"
  },
  {
    "name": "Austria",
    "slug": "austria",
    "countryCode": "AT"
  },
  {
    "name": "Bangladesh",
    "slug": "bangladesh",
    "countryCode": "BD"
  },
  {
    "name": "Belgium",
    "slug": "belgium",
    "countryCode": "BE"
  },
  {
    "name": "Bhutan",
    "slug": "bhutan",
    "countryCode": "BT"
  },
  {
    "name": "Bolivia",
    "slug": "bolivia",
    "countryCode": "BO"
  },
  {
    "name": "Bosnia and Herzegovina",
    "slug": "bosnia-and-herzegovina",
    "countryCode": "BA"
  },
  {
    "name": "Botswana",
    "slug": "botswana",
    "countryCode": "BW"
  },
  {
    "name": "Brazil",
    "slug": "brazil",
    "countryCode": "BR"
  },
  {
    "name": "Bulgaria",
    "slug": "bulgaria",
    "countryCode": "BG"
  },
  {
    "name": "Cambodia",
    "slug": "cambodia",
    "countryCode": "KH"
  },
  {
    "name": "Canada",
    "slug": "canada",
    "countryCode": "CA"
  },
  {
    "name": "Chile",
    "slug": "chile",
    "countryCode": "CL"
  },
  {
    "name": "Colombia",
    "slug": "colombia",
    "countryCode": "CO"
  },
  {
    "name": "Costa Rica",
    "slug": "costa-rica",
    "countryCode": "CR"
  },
  {
    "name": "Croatia",
    "slug": "croatia",
    "countryCode": "HR"
  },
  {
    "name": "Cyprus",
    "slug": "cyprus",
    "countryCode": "CY"
  },
  {
    "name": "Czech Republic",
    "slug": "czech-republic",
    "countryCode": "CZ"
  },
  {
    "name": "Denmark",
    "slug": "denmark",
    "countryCode": "DK"
  },
  {
    "name": "Dominican Republic",
    "slug": "dominican-republic",
    "countryCode": "DO"
  },
  {
    "name": "Ecuador",
    "slug": "ecuador",
    "countryCode": "EC"
  },
  {
    "name": "Estonia",
    "slug": "estonia",
    "countryCode": "EE"
  },
  {
    "name": "Eswatini",
    "slug": "eswatini",
    "countryCode": "SZ"
  },
  {
    "name": "Finland",
    "slug": "finland",
    "countryCode": "FI"
  },
  {
    "name": "France",
    "slug": "france",
    "countryCode": "FR"
  },
  {
    "name": "Germany",
    "slug": "germany",
    "countryCode": "DE"
  },
  {
    "name": "Ghana",
    "slug": "ghana",
    "countryCode": "GH"
  },
  {
    "name": "Greece",
    "slug": "greece",
    "countryCode": "GR"
  },
  {
    "name": "Guatemala",
    "slug": "guatemala",
    "countryCode": "GT"
  },
  {
    "name": "Hungary",
    "slug": "hungary",
    "countryCode": "HU"
  },
  {
    "name": "Iceland",
    "slug": "iceland",
    "countryCode": "IS"
  },
  {
    "name": "India",
    "slug": "india",
    "countryCode": "IN"
  },
  {
    "name": "Indonesia",
    "slug": "indonesia",
    "countryCode": "ID"
  },
  {
    "name": "Ireland",
    "slug": "ireland",
    "countryCode": "IE"
  },
  {
    "name": "Israel",
    "slug": "israel",
    "countryCode": "IL"
  },
  {
    "name": "Italy",
    "slug": "italy",
    "countryCode": "IT"
  },
  {
    "name": "Japan",
    "slug": "japan",
    "countryCode": "JP"
  },
  {
    "name": "Jordan",
    "slug": "jordan",
    "countryCode": "JO"
  },
  {
    "name": "Kenya",
    "slug": "kenya",
    "countryCode": "KE"
  },
  {
    "name": "Latvia",
    "slug": "latvia",
    "countryCode": "LV"
  },
  {
    "name": "Lesotho",
    "slug": "lesotho",
    "countryCode": "LS"
  },
  {
    "name": "Liechtenstein",
    "slug": "liechtenstein",
    "countryCode": "LI"
  },
  {
    "name": "Lithuania",
    "slug": "lithuania",
    "countryCode": "LT"
  },
  {
    "name": "Luxembourg",
    "slug": "luxembourg",
    "countryCode": "LU"
  },
  {
    "name": "Malaysia",
    "slug": "malaysia",
    "countryCode": "MY"
  },
  {
    "name": "Mexico",
    "slug": "mexico",
    "countryCode": "MX"
  },
  {
    "name": "Mongolia",
    "slug": "mongolia",
    "countryCode": "MN"
  },
  {
    "name": "Montenegro",
    "slug": "montenegro",
    "countryCode": "ME"
  },
  {
    "name": "Namibia",
    "slug": "namibia",
    "countryCode": "NA"
  },
  {
    "name": "Nepal",
    "slug": "nepal",
    "countryCode": "NP"
  },
  {
    "name": "Netherlands",
    "slug": "netherlands",
    "countryCode": "NL"
  },
  {
    "name": "New Zealand",
    "slug": "new-zealand",
    "countryCode": "NZ"
  },
  {
    "name": "Nigeria",
    "slug": "nigeria",
    "countryCode": "NG"
  },
  {
    "name": "North Macedonia",
    "slug": "north-macedonia",
    "countryCode": "MK"
  },
  {
    "name": "Norway",
    "slug": "norway",
    "countryCode": "NO"
  },
  {
    "name": "Oman",
    "slug": "oman",
    "countryCode": "OM"
  },
  {
    "name": "Palestine",
    "slug": "palestine",
    "countryCode": "PS"
  },
  {
    "name": "Panama",
    "slug": "panama",
    "countryCode": "PA"
  },
  {
    "name": "Paraguay",
    "slug": "paraguay",
    "countryCode": "PY"
  },
  {
    "name": "Peru",
    "slug": "peru",
    "countryCode": "PE"
  },
  {
    "name": "Philippines",
    "slug": "philippines",
    "countryCode": "PH"
  },
  {
    "name": "Poland",
    "slug": "poland",
    "countryCode": "PL"
  },
  {
    "name": "Portugal",
    "slug": "portugal",
    "countryCode": "PT"
  },
  {
    "name": "Qatar",
    "slug": "qatar",
    "countryCode": "QA"
  },
  {
    "name": "Romania",
    "slug": "romania",
    "countryCode": "RO"
  },
  {
    "name": "Russia",
    "slug": "russia",
    "countryCode": "RU"
  },
  {
    "name": "Rwanda",
    "slug": "rwanda",
    "countryCode": "RW"
  },
  {
    "name": "San Marino",
    "slug": "san-marino",
    "countryCode": "SM"
  },
  {
    "name": "Senegal",
    "slug": "senegal",
    "countryCode": "SN"
  },
  {
    "name": "Serbia",
    "slug": "serbia",
    "countryCode": "RS"
  },
  {
    "name": "Singapore",
    "slug": "singapore",
    "countryCode": "SG"
  },
  {
    "name": "Slovakia",
    "slug": "slovakia",
    "countryCode": "SK"
  },
  {
    "name": "Slovenia",
    "slug": "slovenia",
    "countryCode": "SI"
  },
  {
    "name": "South Africa",
    "slug": "south-africa",
    "countryCode": "ZA"
  },
  {
    "name": "South Korea",
    "slug": "south-korea",
    "countryCode": "KR"
  },
  {
    "name": "Spain",
    "slug": "spain",
    "countryCode": "ES"
  },
  {
    "name": "Sri Lanka",
    "slug": "sri-lanka",
    "countryCode": "LK"
  },
  {
    "name": "Sweden",
    "slug": "sweden",
    "countryCode": "SE"
  },
  {
    "name": "Switzerland",
    "slug": "switzerland",
    "countryCode": "CH"
  },
  {
    "name": "Taiwan",
    "slug": "taiwan",
    "countryCode": "TW"
  },
  {
    "name": "Thailand",
    "slug": "thailand",
    "countryCode": "TH"
  },
  {
    "name": "Tunisia",
    "slug": "tunisia",
    "countryCode": "TN"
  },
  {
    "name": "Turkey",
    "slug": "turkey",
    "countryCode": "TR"
  },
  {
    "name": "Uganda",
    "slug": "uganda",
    "countryCode": "UG"
  },
  {
    "name": "Ukraine",
    "slug": "ukraine",
    "countryCode": "UA"
  },
  {
    "name": "United Arab Emirates",
    "slug": "united-arab-emirates",
    "countryCode": "AE"
  },
  {
    "name": "United Kingdom",
    "slug": "united-kingdom",
    "countryCode": "GB"
  },
  {
    "name": "United States",
    "slug": "united-states",
    "countryCode": "US"
  },
  {
    "name": "Uruguay",
    "slug": "uruguay",
    "countryCode": "UY"
  },
  {
    "name": "Vietnam",
    "slug": "vietnam",
    "countryCode": "VN"
  }
];
