// Regenerates lib/countryMapList.js from public/officialCountryMaps.json:
// just {name, slug, countryCode} per country, sorted by name. pages/maps.js renders the
// list as plain links so every country map has a crawlable link from the
// /maps hub; importing the full JSON there would put every country's
// descriptions into that page's bundle. test/countryMapList.test.js fails
// when this file is stale. Run: node scripts/writeCountryMapList.mjs

import fs from "node:fs";
import path from "node:path";

const src = path.resolve("public/officialCountryMaps.json");
const out = path.resolve("lib/countryMapList.js");
const maps = JSON.parse(fs.readFileSync(src, "utf8"))
  .map((m) => ({ name: m.name, slug: m.slug, countryCode: m.countryCode }))
  .sort((a, b) => a.name.localeCompare(b.name, "en"));

const body = `// GENERATED by scripts/writeCountryMapList.mjs from public/officialCountryMaps.json.
// Do not edit by hand; rerun the script when a country map is added.
export const COUNTRY_MAP_LIST = ${JSON.stringify(maps, null, 2)};
`;
fs.writeFileSync(out, body);
console.log(`[countryMapList] wrote ${maps.length} entries to ${out}`);
