/**
 * GENERATED FILE — DO NOT EDIT BY HAND.
 *
 * The frozen Season 0 closing ladder, collapsed to a rating -> rank lookup.
 * Written by:
 *
 *     node scripts/exportSeason0HallOfFame.js --apply
 *
 * ...which produces this file and public/season0-hall-of-fame.json from the SAME
 * scan, so the rank on a player's profile and their row on the Hall of Fame page
 * can never disagree.
 *
 * WHY A TABLE AND NOT A LIVE COUNT
 * --------------------------------
 * "Rank #431 on the day the ranked update landed" is a historical fact. A
 * countDocuments({ elo_s0: { $gt: x } }) at request time would answer it
 * differently every month as accounts are banned or deleted, would need a new
 * index on a 2M-document collection, and would disagree with the Hall of Fame
 * (which excludes banned / pending-rename / unnamed accounts as of migration
 * day). It cannot change, so it is a file — same reasoning as the board itself.
 *
 * A .js module rather than JSON because api/* is loaded by server.js as plain
 * Node ESM, where importing JSON needs import attributes that vary by Node
 * version. This just imports.
 */

export const SEASON0_RANK_TABLE = {
  schemaVersion: 1,
  /** ISO timestamp of the export, or null while the table is still empty. */
  generatedAt: "2026-08-09T04:33:31.467Z",
  /** Accounts counted into the ranking (the Hall of Fame's eligible population). */
  eligibleAccounts: 49375,
  /** True when generated by a --limit smoke run. Never true in a shipped table. */
  partial: false,
  /**
   * Rounded closing rating (elo_s0) -> competition rank. Equal ratings share a
   * rank and the next distinct rating skips: 1, 2, 2, 4.
   */
  ranks: {
    895: 49375, 924: 49374, 995: 49373, 1000: 13, 1004: 12, 1084: 11, 1123: 10, 1142: 9, 1651: 8, 1684: 7,
    1770: 6, 2114: 5, 2121: 4, 2130: 3, 2300: 2, 2484: 1,
  },
};

export default SEASON0_RANK_TABLE;
